import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/layout";
import Link from "next/link";
import { useState } from "react";
export default function Home() {
  const [onHovers, setOnHovers] = useState([false, false, false]);
  return (
    <>
      <Head>
        <title>Fair Raffle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="left_gradient" />
        <div className="right_gradient" />
        <main className={styles.main}>
          <div className={styles.container}>
            <div className={styles.body}>
              <Image
                src="/png/fairraffle.png"
                alt="raffle"
                height={500}
                width={500}
              />
              <div className={styles.body_text}>
                <div className={styles.heros}>
                  <div className={styles.hero}>
                    <Image
                      src="/svg/starknet.svg"
                      alt="discord"
                      height={32}
                      width={32}
                    />
                    <h3 className={styles.hero_title}>On Starknet </h3>
                  </div>
                  {/* <div className={styles.hero}>
                    <Image
                      src="/svg/starknet.svg"
                      alt="discord"
                      height={32}
                      width={32}
                    />
                    <h3 className={styles.hero_title}>On Starknet </h3>
                  </div> */}
                </div>
                <h1 className={styles.title}>TRUSTLESS & on-cHAIN</h1>
                <h2 className={styles.subtitle}>Raffle Tool</h2>
                <div className={styles.body_option}>
                  <div className={styles.body_option_item}>
                    <Image
                      src="/svg/github.svg"
                      alt="1"
                      height={32}
                      width={32}
                    />
                    <div className={styles.body_option_item_text}>
                      <label className={styles.label}>
                        Totally Open Source
                      </label>
                      <label className={styles.label}>For Community</label>
                    </div>
                  </div>
                  <div className={styles.body_option_item}>
                    <Image
                      src="/png/onlyDust.png"
                      alt="1"
                      height={32}
                      width={32}
                    />
                    <div className={styles.body_option_item_text}>
                      <label className={styles.label}>
                        Only Dust TLV Hacker House
                      </label>
                      <label className={styles.label}>Finalist</label>
                    </div>
                  </div>
                  {/* <div className={styles.body_option_item}>
                    <Image
                      src="/svg/black.svg"
                      alt="1"
                      height={32}
                      width={32}
                    />
                    <div className={styles.body_option_item_text}>
                      <label className={styles.label}>VRF SPONSOR</label>
                      <label className={styles.label}>- </label>
                    </div>
                  </div> */}
                  <div className={styles.partner}>
                    <label className={styles.partner_label}>
                      Partner Project
                    </label>
                    <div className={styles.partner_button}>
                      <Link href="/collection/1">Lucky Cookies</Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.footer}>
              <div className={styles.footer_item}>
                <label className={styles.label}>Make A Raffle With</label>
                <span
                  href="/make-raffle/list"
                  className={styles.button}
                  onMouseEnter={() => setOnHovers([true, false, false])}
                  onMouseLeave={() => setOnHovers([false, false, false])}
                >
                  {onHovers[0] ? "DEVELOPING" : "LIST"}
                </span>
              </div>
              <div className={styles.footer_item}>
                <label className={styles.label}>Make A Raffle With</label>
                <>
                  <span
                    href="make-raffle/collection"
                    className={styles.button}
                    onMouseEnter={() => setOnHovers([false, true, false])}
                    onMouseLeave={() => setOnHovers([false, false, false])}
                  >
                    {onHovers[1] ? "DEVELOPING" : "NFT Collection"}
                  </span>
                </>
              </div>
              <div className={styles.footer_item}>
                <label className={styles.label}>Make A Raffle With</label>
                <span
                  href={"make-raffle/twitter"}
                  className={styles.button}
                  onMouseEnter={() => setOnHovers([false, false, true])}
                  onMouseLeave={() => setOnHovers([false, false, false])}
                >
                  {onHovers[2] ? "DEVELOPING" : "TWITTER"}
                </span>
              </div>
            </div>
          </div>
        </main>
      </Layout>
    </>
  );
}
