import Head from "next/head";
import styles from "@/styles/PastRaffles.module.css";
import Layout from "@/components/layout";
import { useEffect } from "react";
import { useState } from "react";
import { getContract } from "./api/hello";
import Header from "@/components/header";
import RaffleTable from "@/components/table";

export default function Raffles() {
  const [raffles, setRaffles] = useState([]);

  const getRaffles = async () => {
    const contract = await getContract();
    const raffleCount = await contract.lastRaffleId();

    const _raffles = [];
    for (let i = 0; i < raffleCount; i++) {
      const raffle = await contract.raffles(i + 1);
      console.log(raffle.requestStatus.fulfilled);
      _raffles.push({
        owner: raffle.owner,
        status: raffle.status?.toString(),
        name: raffle.name,
        id: raffle.id.toString(),
        raffleListIpfsHash: raffle.raffleListIpfsHash,
        numberOfTickets: raffle.numberOfTickets?.toString(),
        numberOfWinners: raffle.numberOfWinners?.toString(),
        time: raffle.time?.toString(),
      });
    }

    setRaffles(_raffles);
  };

  useEffect(() => {
    getRaffles();
  }, []);

  return (
    <>
      <Head>
        <title>Past Raffles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="left_gradient" />
        <div className="right_gradient" />
        <main className={styles.main}>
          <Header
            title="ALL PAST RAFFLES"
            texts={[
              "You can check out past raffles anytime via that page. Just click to results. Never trust, verify.",
            ]}
          />
          <div className={styles.raffles}>
            <RaffleTable raffles={raffles} />
          </div>
        </main>
      </Layout>
    </>
  );
}
